### ISSUE TITLE
[Documentation] Add guide on how to group devices

### ISSUE THREAD

**Issue by avendretter** [seydx/homebridge-fritz-platform#252]
Hey there,

I am struggling to group two Dect!301 thermostats together.

If I add then in the plugin to be part of a group, nothing happens.
<img width="382" alt="Screenshot 2021-11-19 at 12 09 03" src="https://user-images.githubusercontent.com/1587171/142612980-a62e8fe9-0dc4-4165-8c3b-caf4ceef7d47.png">

I tried to create a group in my Fritz!box and adding a device without an AIN using the GUI. But by doing that the plugin is not finding the two thermostats with the AIN
```bash
[11/19/2021, 12:10:35 PM] [FritzPlatform] Therm-1 (smarthome-thermostat): Can not find device with AIN: 099950100114
[11/19/2021, 12:10:35 PM] [FritzPlatform] Therm-2 (smarthome-thermostat): Can not find device with AIN: 099950050431
``` 
AND its ignoring the group device since there is no AIN set.

After trying out things back and forth I got a working config. This included adding a group in my Fritz!Box the the name `WoZi`.
This config will add the single devices as well as the group. 
```yaml
"smarthome": [
                {
                    "active": true,
                    "name": "Therm-WoZi1",
                    "ain": "09995 0100114",
                    "temperature": true,
                    "battery": true,
                    "accType": "thermostat"
                },
                {
                    "active": true,
                    "name": "Therm-WoZi2",
                    "ain": "09995 0050431",
                    "temperature": true,
                    "battery": true,
                    "accType": "thermostat"
                },
                {
                    "active": true,
                    "name": "WoZi",
                    "group": true,
                    "temperature": true,
                    "battery": true,
                    "accTypeGroup": "thermostat",
                    "accType": "thermostat"
                }
            ],
```
